2024-03-15 20:14:25,982 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-15 20:14:25,982 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Configure stats pid to 15036
2024-03-15 20:14:25,982 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Loading settings from C:\Users\loreb\.config\wandb\settings
2024-03-15 20:14:25,983 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Loading settings from c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\settings
2024-03-15 20:14:25,983 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-15 20:14:25,983 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-15 20:14:25,983 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-15 20:14:25,984 INFO    MainThread:15036 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_201425-h6917tgp\logs\debug.log
2024-03-15 20:14:25,984 INFO    MainThread:15036 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_201425-h6917tgp\logs\debug-internal.log
2024-03-15 20:14:25,984 INFO    MainThread:15036 [wandb_init.py:init():566] calling init triggers
2024-03-15 20:14:25,984 INFO    MainThread:15036 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'architecture': 'MLP', 'dataset': 'MNIST', 'epochs': 100}
2024-03-15 20:14:25,984 INFO    MainThread:15036 [wandb_init.py:init():616] starting backend
2024-03-15 20:14:25,985 INFO    MainThread:15036 [wandb_init.py:init():620] setting up manager
2024-03-15 20:14:26,061 ERROR   MainThread:15036 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\wandb_init.py", line 621, in init
    manager._inform_init(
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\service\service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] Connessione in corso interrotta forzatamente dall'host remoto
