2024-03-15 20:11:46,116 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-15 20:11:46,117 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Configure stats pid to 15036
2024-03-15 20:11:46,117 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Loading settings from C:\Users\loreb\.config\wandb\settings
2024-03-15 20:11:46,117 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Loading settings from c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\settings
2024-03-15 20:11:46,117 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-15 20:11:46,117 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-15 20:11:46,117 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-15 20:11:46,118 INFO    MainThread:15036 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_201146-56v8yxtf\logs\debug.log
2024-03-15 20:11:46,118 INFO    MainThread:15036 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_201146-56v8yxtf\logs\debug-internal.log
2024-03-15 20:11:46,118 INFO    MainThread:15036 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000019A08CAC4D0>
2024-03-15 20:11:46,118 INFO    MainThread:15036 [wandb_init.py:init():566] calling init triggers
2024-03-15 20:11:46,118 INFO    MainThread:15036 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'architecture': 'MLP', 'dataset': 'MNIST', 'epochs': 100}
2024-03-15 20:11:46,118 INFO    MainThread:15036 [wandb_init.py:init():591] re-initializing run, found existing run on stack: t9wotqaj
2024-03-15 20:11:46,120 INFO    MainThread:15036 [wandb_run.py:_finish():1970] finishing run lorebaia/DLA Assigment 1/t9wotqaj
2024-03-15 20:11:46,121 INFO    MainThread:15036 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-15 20:11:46,121 INFO    MainThread:15036 [wandb_run.py:_restore():2193] restore
2024-03-15 20:11:46,121 INFO    MainThread:15036 [wandb_run.py:_restore():2199] restore done
2024-03-15 20:13:06,772 INFO    MainThread:15036 [wandb_init.py:init():616] starting backend
2024-03-15 20:13:06,772 INFO    MainThread:15036 [wandb_init.py:init():620] setting up manager
2024-03-15 20:13:06,774 INFO    MainThread:15036 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-15 20:13:06,775 INFO    MainThread:15036 [wandb_init.py:init():628] backend started and connected
2024-03-15 20:13:06,778 INFO    MainThread:15036 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-15 20:13:06,778 INFO    MainThread:15036 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-15 20:13:06,778 INFO    MainThread:15036 [wandb_init.py:init():720] updated telemetry
2024-03-15 20:13:06,815 INFO    MainThread:15036 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-15 20:13:41,028 WARNING MainThread:15036 [wandb_init.py:init():1198] interrupted
Traceback (most recent call last):
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\wandb_init.py", line 756, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-03-15 20:13:43,893 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-15 20:13:43,893 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Configure stats pid to 15036
2024-03-15 20:13:43,893 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Loading settings from C:\Users\loreb\.config\wandb\settings
2024-03-15 20:13:43,893 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Loading settings from c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\settings
2024-03-15 20:13:43,893 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-15 20:13:43,893 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-15 20:13:43,894 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-15 20:13:43,894 INFO    MainThread:15036 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_201343-pk5hv5qd\logs\debug.log
2024-03-15 20:13:43,894 INFO    MainThread:15036 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_201343-pk5hv5qd\logs\debug-internal.log
2024-03-15 20:13:43,894 INFO    MainThread:15036 [wandb_init.py:init():566] calling init triggers
2024-03-15 20:13:43,894 INFO    MainThread:15036 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'architecture': 'MLP', 'dataset': 'MNIST', 'epochs': 100}
2024-03-15 20:13:43,895 INFO    MainThread:15036 [wandb_init.py:init():616] starting backend
2024-03-15 20:13:43,895 INFO    MainThread:15036 [wandb_init.py:init():620] setting up manager
2024-03-15 20:13:43,897 INFO    MainThread:15036 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-15 20:13:43,897 INFO    MainThread:15036 [wandb_init.py:init():628] backend started and connected
2024-03-15 20:13:43,901 INFO    MainThread:15036 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-15 20:13:43,901 INFO    MainThread:15036 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-15 20:13:43,901 INFO    MainThread:15036 [wandb_init.py:init():720] updated telemetry
2024-03-15 20:13:44,325 INFO    MainThread:15036 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-15 20:13:47,364 WARNING MainThread:15036 [wandb_init.py:init():1198] interrupted
Traceback (most recent call last):
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\wandb_init.py", line 756, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-03-15 20:13:48,283 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-15 20:13:48,283 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Configure stats pid to 15036
2024-03-15 20:13:48,283 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Loading settings from C:\Users\loreb\.config\wandb\settings
2024-03-15 20:13:48,283 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Loading settings from c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\settings
2024-03-15 20:13:48,283 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-15 20:13:48,283 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-15 20:13:48,284 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-15 20:13:48,284 INFO    MainThread:15036 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_201348-10fg52uo\logs\debug.log
2024-03-15 20:13:48,284 INFO    MainThread:15036 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_201348-10fg52uo\logs\debug-internal.log
2024-03-15 20:13:48,285 INFO    MainThread:15036 [wandb_init.py:init():566] calling init triggers
2024-03-15 20:13:48,285 INFO    MainThread:15036 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'architecture': 'MLP', 'dataset': 'MNIST', 'epochs': 100}
2024-03-15 20:13:48,285 INFO    MainThread:15036 [wandb_init.py:init():616] starting backend
2024-03-15 20:13:48,285 INFO    MainThread:15036 [wandb_init.py:init():620] setting up manager
2024-03-15 20:13:48,288 INFO    MainThread:15036 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-15 20:13:48,288 INFO    MainThread:15036 [wandb_init.py:init():628] backend started and connected
2024-03-15 20:13:48,292 INFO    MainThread:15036 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-15 20:13:48,292 INFO    MainThread:15036 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-15 20:13:48,292 INFO    MainThread:15036 [wandb_init.py:init():720] updated telemetry
2024-03-15 20:13:48,329 INFO    MainThread:15036 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-15 20:14:04,304 WARNING MsgRouterThr:15036 [router.py:message_loop():77] message_loop has been closed
2024-03-15 20:14:04,304 WARNING MsgRouterThr:15036 [router.py:message_loop():77] message_loop has been closed
2024-03-15 20:14:04,304 WARNING MsgRouterThr:15036 [router.py:message_loop():77] message_loop has been closed
2024-03-15 20:14:04,304 WARNING MsgRouterThr:15036 [router.py:message_loop():77] message_loop has been closed
2024-03-15 20:14:08,653 ERROR   MainThread:15036 [wandb_init.py:init():1194] transport failed
Traceback (most recent call last):
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\wandb_init.py", line 756, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
2024-03-15 20:14:25,982 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-15 20:14:25,982 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Configure stats pid to 15036
2024-03-15 20:14:25,982 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Loading settings from C:\Users\loreb\.config\wandb\settings
2024-03-15 20:14:25,983 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Loading settings from c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\settings
2024-03-15 20:14:25,983 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-15 20:14:25,983 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-15 20:14:25,983 INFO    MainThread:15036 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-15 20:14:25,984 INFO    MainThread:15036 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_201425-h6917tgp\logs\debug.log
2024-03-15 20:14:25,984 INFO    MainThread:15036 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_201425-h6917tgp\logs\debug-internal.log
2024-03-15 20:14:25,984 INFO    MainThread:15036 [wandb_init.py:init():566] calling init triggers
2024-03-15 20:14:25,984 INFO    MainThread:15036 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'architecture': 'MLP', 'dataset': 'MNIST', 'epochs': 100}
2024-03-15 20:14:25,984 INFO    MainThread:15036 [wandb_init.py:init():616] starting backend
2024-03-15 20:14:25,985 INFO    MainThread:15036 [wandb_init.py:init():620] setting up manager
2024-03-15 20:14:26,061 ERROR   MainThread:15036 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\wandb_init.py", line 621, in init
    manager._inform_init(
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\service\service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] Connessione in corso interrotta forzatamente dall'host remoto
